force-app/main/default/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/main/default/objects/Employee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/main/default/classes/sObjectDemo.cls
public class sObjectDemo {
    public static ID createAccount(){
        Account acc = new Account();
		acc.Name = 'Test';
        acc.Phone = '8652685823';
		acc.Active__c = 'Yes';
        insert acc;
        return acc.Id;
    }
    
    public static void createContact(){
        Contact con = new Contact();
        con.FirstName = 'John';
        con.LastName = 'Doe';
        con.Phone = '8652685823';
        con.Email = 'john.doe@test.com';

        insert con;
    }
    
     public static void createOpportunity(){

        Opportunity opp = new Opportunity();
        opp.Name = 'New Business Deal';
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today().addDays(30);

        insert opp;
    }

    public static void createEmployee() {
        Account acc = [
            SELECT Id
            FROM Account
            WHERE Name = 'MGREWQ'
            LIMIT 1
        ];
        Employee__c emp = new Employee__c(
            Name = 'John Smith',
            Salary__c = 75000,
            Department__c = 'IT',
            Account__c = acc.Id
        );
    
    	insert emp;
    }
    
     public static void createEmployee2() {
        Employee__c emp = new Employee__c();
         	Id accId = createAccount();
            emp.Name = 'Rushikesh Raut';
            emp.Salary__c = 100000;
            emp.Department__c = 'Finance';
         	emp.Account__c = accId;
    		insert emp;
    }
}